<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the patients table with initial data.
     */
    public function run()
    {
        DB::table('patients')->insert([
            [
                'patientId' => 14,
                'nin' => 9383838,
                'userId' => 31,
                'chfId' => 'CHF-ABUTH-617490328E',
                'hospitalFileNumber' => 9393,
                'hospital' => 1,
                'stateOfOrigin' => 17,
                'stateOfResidence' => 1,
                'religion' => 'Anglican',
                'gender' => 'Female',
                'bloodGroup' => 'AB+',
                'occupation' => 'Banker',
                'dateOfBirth' => '2025-04-01',
                'address' => null,
                'nextOfKinName' => 'Shehu Sani',
                'nextOfKinAddress' => 'No 4 Tchibanga close off Durban street off, Adetokunbo Ademola Crescent, Wuse 2',
                'nextOfKinPhoneNumber' => 08132743258,
                'nextOfKinEmail' => null,
                'nextOfKinRelationship' => 'Sister',
                'nextOfKinOccupation' => 'Carpenter',
                'nextOfKinGender' => 'Male',
                'hmo' => 16,
                'hmoNumber' => 93003,
                'cancer' => 1,
                'cancerStage' => null,
                'doctor' => 7,
                'status' => 4,
                'created_at' => '2025-04-24 16:38:59',
                'updated_at' => '2025-04-25 08:21:52',
                'deleted_at' => null
            ],
            [
                'patientId' => 17,
                'nin' => null,
                'userId' => null,
                'chfId' => null,
                'hospitalFileNumber' => 890,
                'hospital' => null,
                'stateOfOrigin' => 37,
                'stateOfResidence' => 8,
                'religion' => null,
                'gender' => 'Male',
                'bloodGroup' => null,
                'occupation' => null,
                'dateOfBirth' => '2025-12-14',
                'address' => null,
                'nextOfKinName' => null,
                'nextOfKinAddress' => null,
                'nextOfKinPhoneNumber' => null,
                'nextOfKinEmail' => null,
                'nextOfKinRelationship' => null,
                'nextOfKinOccupation' => null,
                'nextOfKinGender' => null,
                'hmo' => null,
                'hmoNumber' => null,
                'cancer' => null,
                'cancerStage' => null,
                'doctor' => null,
                'status' => 2,
                'created_at' => '2025-12-14 04:14:05',
                'updated_at' => '2025-12-14 04:14:05',
                'deleted_at' => null
            ],
            [
                'patientId' => 18,
                'nin' => null,
                'userId' => null,
                'chfId' => null,
                'hospitalFileNumber' => 90,
                'hospital' => null,
                'stateOfOrigin' => 37,
                'stateOfResidence' => 15,
                'religion' => null,
                'gender' => 'Male',
                'bloodGroup' => null,
                'occupation' => null,
                'dateOfBirth' => '2025-12-20',
                'address' => null,
                'nextOfKinName' => null,
                'nextOfKinAddress' => null,
                'nextOfKinPhoneNumber' => null,
                'nextOfKinEmail' => null,
                'nextOfKinRelationship' => null,
                'nextOfKinOccupation' => null,
                'nextOfKinGender' => null,
                'hmo' => null,
                'hmoNumber' => null,
                'cancer' => null,
                'cancerStage' => null,
                'doctor' => null,
                'status' => 2,
                'created_at' => '2025-12-14 04:22:01',
                'updated_at' => '2025-12-14 04:22:01',
                'deleted_at' => null
            ],
            [
                'patientId' => 19,
                'nin' => null,
                'userId' => null,
                'chfId' => null,
                'hospitalFileNumber' => 90,
                'hospital' => null,
                'stateOfOrigin' => 37,
                'stateOfResidence' => 15,
                'religion' => null,
                'gender' => 'Male',
                'bloodGroup' => null,
                'occupation' => null,
                'dateOfBirth' => '2025-12-20',
                'address' => null,
                'nextOfKinName' => null,
                'nextOfKinAddress' => null,
                'nextOfKinPhoneNumber' => null,
                'nextOfKinEmail' => null,
                'nextOfKinRelationship' => null,
                'nextOfKinOccupation' => null,
                'nextOfKinGender' => null,
                'hmo' => null,
                'hmoNumber' => null,
                'cancer' => null,
                'cancerStage' => null,
                'doctor' => null,
                'status' => 2,
                'created_at' => '2025-12-14 04:34:21',
                'updated_at' => '2025-12-14 04:34:21',
                'deleted_at' => null
            ],
            [
                'patientId' => 20,
                'nin' => null,
                'userId' => null,
                'chfId' => null,
                'hospitalFileNumber' => 90,
                'hospital' => null,
                'stateOfOrigin' => 37,
                'stateOfResidence' => 15,
                'religion' => null,
                'gender' => 'Male',
                'bloodGroup' => null,
                'occupation' => null,
                'dateOfBirth' => '2025-12-20',
                'address' => null,
                'nextOfKinName' => null,
                'nextOfKinAddress' => null,
                'nextOfKinPhoneNumber' => null,
                'nextOfKinEmail' => null,
                'nextOfKinRelationship' => null,
                'nextOfKinOccupation' => null,
                'nextOfKinGender' => null,
                'hmo' => null,
                'hmoNumber' => null,
                'cancer' => null,
                'cancerStage' => null,
                'doctor' => null,
                'status' => 2,
                'created_at' => '2025-12-14 04:43:33',
                'updated_at' => '2025-12-14 04:43:33',
                'deleted_at' => null
            ],
            [
                'patientId' => 29,
                'nin' => 90,
                'userId' => 68,
                'chfId' => 'NCCF-NHA-210859473F',
                'hospitalFileNumber' => 9,
                'hospital' => 5,
                'stateOfOrigin' => 23,
                'stateOfResidence' => 22,
                'religion' => null,
                'gender' => 'Other',
                'bloodGroup' => 'AB+',
                'occupation' => 'Civil Engineer',
                'dateOfBirth' => '2025-12-12',
                'address' => 'k',
                'nextOfKinName' => 9,
                'nextOfKinAddress' => 'Suite 308, Nawa Complex, Jahi District\nAhmadu Bello Way, Jahi District',
                'nextOfKinPhoneNumber' => 9,
                'nextOfKinEmail' => 'info@resilience.ng',
                'nextOfKinRelationship' => 'Wife',
                'nextOfKinOccupation' => 'Carpenter',
                'nextOfKinGender' => 'Other',
                'hmo' => 1,
                'hmoNumber' => null,
                'cancer' => 3,
                'cancerStage' => null,
                'doctor' => null,
                'status' => 2,
                'created_at' => '2025-12-14 17:37:19',
                'updated_at' => '2025-12-14 17:37:19',
                'deleted_at' => null
            ]
        ]);
    }
}