<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the users table with initial data.
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'firstName' => 'Victor',
                'lastName' => 'Oseji',
                'otherNames' => null,
                'email' => 'superadmin1@gmail.com',
                'phoneNumber' => 08137054870,
                'password' => '$2y$12$Ior.qtpPRZGM2LuOfCsdYuiINqMRGdsvPQmrNf7/7.DEgxdC8Tg5q',
                'email_verified_at' => null,
                'role' => 12,
                'remember_token' => null,
                'created_at' => '2025-02-07 09:20:30',
                'updated_at' => '2025-02-07 09:20:30',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 3,
                'firstName' => 'Lukeman',
                'lastName' => 'Lukeman',
                'otherNames' => null,
                'email' => 'nicratict@gmail.com',
                'phoneNumber' => 0813456780,
                'password' => '$2y$12$wch7th7AZ1orW6dWwMxR4.7rYrQLFTLvprzPJzN0Eti.fzw9f1TEO',
                'email_verified_at' => null,
                'role' => 10,
                'remember_token' => null,
                'created_at' => '2025-02-07 09:54:56',
                'updated_at' => '2025-02-07 09:54:56',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 4,
                'firstName' => 'John',
                'lastName' => 'Doe',
                'otherNames' => null,
                'email' => 'hospitaladmin@gmail.com',
                'phoneNumber' => 0000000000,
                'password' => '$2y$12$HSVjArilQAQdoKjqrofBj.IfMdznXyFuNc04s9DTJP.uwoNniUxhe',
                'email_verified_at' => null,
                'role' => 6,
                'remember_token' => null,
                'created_at' => '2025-02-07 10:42:28',
                'updated_at' => '2025-02-07 10:42:28',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 5,
                'firstName' => 'ABUTH',
                'lastName' => 'CMD',
                'otherNames' => null,
                'email' => 'cmd@gmail.com',
                'phoneNumber' => 1111111111,
                'password' => '$2y$12$0pGeT2xE5lTs/Dqd/2C50.HWgD7RiX.9aHUnAGZMn0Jy5wdGcC3vm',
                'email_verified_at' => null,
                'role' => 7,
                'remember_token' => null,
                'created_at' => '2025-02-07 10:46:09',
                'updated_at' => '2025-02-07 10:46:09',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 7,
                'firstName' => 'Doctor',
                'lastName' => 1,
                'otherNames' => null,
                'email' => 'doctor1@gmail.com',
                'phoneNumber' => 333333333,
                'password' => '$2y$12$fa7SDS2PrTQfFdTt5Ytwi.grEbY1JtboYLda7JC/gV2ay7v0CH6F2',
                'email_verified_at' => null,
                'role' => 2,
                'remember_token' => null,
                'created_at' => '2025-02-07 11:39:24',
                'updated_at' => '2025-02-07 11:39:24',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 31,
                'firstName' => 'Patient',
                'lastName' => 'One',
                'otherNames' => null,
                'email' => 'patient1@gmail.com',
                'phoneNumber' => 08137054875,
                'password' => '$2y$12$fvk6MPgS0FFW1NFS3lL4MeYWJ2/gPLBwMx2WsRdsdw6iM/OTmFp7S',
                'email_verified_at' => null,
                'role' => 1,
                'remember_token' => null,
                'created_at' => '2025-02-09 12:19:52',
                'updated_at' => '2025-02-09 12:19:52',
                'deleted_at' => null,
                'languageId' => 3,
                'doctorId' => null
            ],
            [
                'id' => 33,
                'firstName' => 'Patient',
                'lastName' => 'Two',
                'otherNames' => null,
                'email' => 'patient2@gmail.com',
                'phoneNumber' => 08119179755,
                'password' => '$2y$12$6vqLC/TarW/vDinViVFFoege/AhIBb.RoZ5f68I3V84hfFK0KVAZG',
                'email_verified_at' => null,
                'role' => 1,
                'remember_token' => null,
                'created_at' => '2025-02-10 10:58:14',
                'updated_at' => '2025-02-10 10:58:14',
                'deleted_at' => null,
                'languageId' => 2,
                'doctorId' => null
            ],
            [
                'id' => 34,
                'firstName' => 'Social',
                'lastName' => 'Welfare',
                'otherNames' => null,
                'email' => 'socialwelfare1@gmail.com',
                'phoneNumber' => 444444444,
                'password' => '$2y$12$Yy.b.VobkUct0Po0t/auWuKWw9Et8ycdfL/iyOvC.hZOgF455QzMa',
                'email_verified_at' => null,
                'role' => 3,
                'remember_token' => null,
                'created_at' => '2025-02-10 15:13:43',
                'updated_at' => '2025-02-10 15:13:43',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 35,
                'firstName' => 'Simeon',
                'lastName' => 'Nguban',
                'otherNames' => null,
                'email' => 'doctor3@gmail.com',
                'phoneNumber' => 0812348575,
                'password' => '$2y$12$zyU7AYEofEBP4c99LYJCduO98pgJwoe3l71uuRqL8Rv57mys4lZkG',
                'email_verified_at' => null,
                'role' => 6,
                'remember_token' => null,
                'created_at' => '2025-02-10 20:14:33',
                'updated_at' => '2025-02-10 20:14:33',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 36,
                'firstName' => 'MDT',
                'lastName' => 'One',
                'otherNames' => null,
                'email' => 'mdt1@gmail.com',
                'phoneNumber' => 909993939,
                'password' => '$2y$12$WJy2a1iHyoXCoKqoDQ5IjOmweRUhi8sSuEbZzmWFueVLfjmZuZgWy',
                'email_verified_at' => null,
                'role' => 4,
                'remember_token' => null,
                'created_at' => '2025-02-10 23:38:13',
                'updated_at' => '2025-02-10 23:38:13',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 37,
                'firstName' => 'DG',
                'lastName' => 'NICRAT',
                'otherNames' => null,
                'email' => 'nicratdg@gmail.com',
                'phoneNumber' => 0819999999,
                'password' => '$2y$12$TyQSd3N4285fYeBLLdGiF.pKpTKQhBabMFIXYEhsrJlP0B33lzl5e',
                'email_verified_at' => null,
                'role' => 11,
                'remember_token' => null,
                'created_at' => '2025-02-11 02:13:11',
                'updated_at' => '2025-02-11 02:13:11',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 41,
                'firstName' => 'NICRAT',
                'lastName' => 'Finance Department',
                'otherNames' => null,
                'email' => 'nicratfanda@gmail.com',
                'phoneNumber' => 019192929,
                'password' => '$2y$12$cGZzKHtwTanEpu69kGkGOuYq1MZd0gxusbmaaPF1Q8iFgYwkKgGRe',
                'email_verified_at' => null,
                'role' => 9,
                'remember_token' => null,
                'created_at' => '2025-02-13 11:49:14',
                'updated_at' => '2025-02-13 11:49:14',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 54,
                'firstName' => 'Pharmacist',
                'lastName' => 'One',
                'otherNames' => null,
                'email' => 'pharmacist1@gmail.com',
                'phoneNumber' => 09023465757,
                'password' => '$2y$12$Fdvg/b0xe04c1o0ba6pFM.yQJ.kT0jKdnMuzwiCk4KcgNLs4Q4xf2',
                'email_verified_at' => null,
                'role' => 13,
                'remember_token' => null,
                'created_at' => '2025-02-16 08:26:02',
                'updated_at' => '2025-02-16 08:26:02',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ],
            [
                'id' => 68,
                'firstName' => 'Victor',
                'lastName' => 'Oseji',
                'otherNames' => 'Ogorchukwu',
                'email' => 'vctroseji@gmail.com',
                'phoneNumber' => 07046919327,
                'password' => '$2y$12$DOHd/INgZyOTBdSrwB1aXuZSh.St0eRHAxvy4kUP8mciua05T2gnK',
                'email_verified_at' => null,
                'role' => 1,
                'remember_token' => null,
                'created_at' => '2025-12-14 03:26:45',
                'updated_at' => '2025-12-14 03:26:45',
                'deleted_at' => null,
                'languageId' => null,
                'doctorId' => null
            ]
        ]);
    }
}